In [7]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Lenovo\Downloads\Unicorn\Unicorn_Companies.csv")

print(df.head())

      Company Valuation ($B) Date Joined        Country           City  \
0   Bytedance           $140    4/7/2017          China        Beijing
1      SpaceX         $100.3   12/1/2012  United States      Hawthorne
2      Stripe            $95   1/23/2014  United States  San Francisco
3      Klarna          $45.6  12/12/2011         Sweden      Stockholm
4  Epic Games            $42  10/26/2018  United States           Cary

                  Industry                                  Select Inverstors  \
0  Artificial intelligence  Sequoia Capital China, SIG Asia Investments, S...
1                    Other  Founders Fund, Draper Fisher Jurvetson, Rothen...
2                  Fintech        Khosla Ventures, LowercaseCapital, capitalG
3                  Fintech  Institutional Venture Partners, Sequoia Capita...
4                    Other              Tencent Holdings, KKR, Smash Ventures

   Founded Year Total Raised Financial Stage  Investors Count  Deal Terms  \
0        2012.0       $7.44B             IPO             28.0         8.0
1        2002.0      $6.874B             NaN             29.0        12.0
2        2010.0      $2.901B           Asset             39.0        12.0
3        2005.0      $3.472B        Acquired             56.0        13.0
4        1991.0      $4.377B        Acquired             25.0         5.0

   Portfolio Exits
0              5.0
1              NaN
2              1.0
3              1.0
4              2.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            1037 non-null   object
 1   Valuation ($B)     1037 non-null   object
 2   Date Joined        1037 non-null   object
 3   Country            1037 non-null   object
 4   City               1037 non-null   object
 5   Industry           1037 non-null   object
 6   Select Inverstors  1020 non-null   object
 7   Founded Year       994 non-null    float64
 8   Total Raised       1013 non-null   object
 9   Financial Stage    49 non-null     object
 10  Investors Count    1036 non-null   float64
 11  Deal Terms         1008 non-null   float64
 12  Portfolio Exits    49 non-null     float64
dtypes: float64(4), object(9)
memory usage: 105.4+ KB

In [10]:
df.shape

(1037, 13)

In [11]:
df.isnull().sum()

Company                0
Valuation ($B)         0
Date Joined            0
Country                0
City                   0
Industry               0
Select Inverstors     17
Founded Year          43
Total Raised          24
Financial Stage      988
Investors Count        1
Deal Terms            29
Portfolio Exits      988
dtype: int64

In [12]:
df['Valuation ($B)'] = (
    df['Valuation ($B)']
    .str.replace('$', '', regex=False)
    .astype(float)
)

In [13]:
df['Valuation ($B)'].head()

0    140.0
1    100.3
2     95.0
3     45.6
4     42.0
Name: Valuation ($B), dtype: float64

In [14]:
df['Date Joined'] = pd.to_datetime(df['Date Joined'])

In [15]:
df['Date Joined'].head()

0   2017-04-07
1   2012-12-01
2   2014-01-23
3   2011-12-12
4   2018-10-26
Name: Date Joined, dtype: datetime64[ns]

In [16]:
df['Year Joined'] = df['Date Joined'].dt.year

In [17]:
df[['Date Joined','Year Joined']].head()

  Date Joined  Year Joined
0  2017-04-07         2017
1  2012-12-01         2012
2  2014-01-23         2014
3  2011-12-12         2011
4  2018-10-26         2018

✔ Converted Valuation from text → numeric
✔ Converted Date Joined from text → datetime
✔ Created a new Year Joined feature

In [18]:
df.dtypes

Company                      object
Valuation ($B)              float64
Date Joined          datetime64[ns]
Country                      object
City                         object
Industry                     object
Select Inverstors            object
Founded Year                float64
Total Raised                 object
Financial Stage              object
Investors Count             float64
Deal Terms                  float64
Portfolio Exits             float64
Year Joined                   int32
dtype: object

Total Unicorns

In [19]:
df['Company'].nunique()

1035

Total Countries

In [20]:
df['Country'].nunique()

46

Total Industries

In [21]:
df['Industry'].nunique()

33

Total Valuation

In [22]:
df['Valuation ($B)'].sum()

np.float64(3413.8900000000003)

Top 10 Countries

In [23]:
df['Country'].value_counts().head(10)

Country
United States     536
China             168
India              63
United Kingdom     42
Germany            24
France             24
Israel             20
Canada             19
Brazil             16
South Korea        12
Name: count, dtype: int64

Top 10 Industries

In [24]:
df['Industry'].value_counts().head(10)

Industry
Fintech                                205
Internet software & services           192
E-commerce & direct-to-consumer        107
Artificial intelligence                 71
Health                                  69
Supply chain, logistics, & delivery     57
Other                                   56
Cybersecurity                           49
Data management & analytics             41
Mobile & telecommunications             37
Name: count, dtype: int64

Unicorns Created by Year

In [25]:
df['Year Joined'].value_counts().sort_index()

Year Joined
2007      1
2011      2
2012      4
2013      3
2014     13
2015     35
2016     21
2017     44
2018    103
2019    107
2020    107
2021    514
2022     83
Name: count, dtype: int64

Let's start learning groupby(), because it's basically the Pandas equivalent of SQL's GROUP BY.

In [26]:
df.groupby('Country')['Valuation ($B)'].sum().sort_values(ascending=False).head(10)

Country
United States     1829.74
China              572.69
India              187.05
United Kingdom     177.68
Germany             66.70
Sweden              60.52
Australia           50.60
France              49.87
Canada              49.03
Israel              38.42
Name: Valuation ($B), dtype: float64

Which industries have the highest total valuation?

In [27]:
df.groupby('Industry')['Valuation ($B)'].sum().sort_values(ascending=False).head(10)

Industry
Fintech                                784.82
Internet software & services           556.13
E-commerce & direct-to-consumer        325.39
Artificial intelligence                308.39
Other                                  265.20
Health                                 182.52
Supply chain, logistics, & delivery    174.76
Data management & analytics            135.84
Cybersecurity                          122.70
Hardware                               101.15
Name: Valuation ($B), dtype: float64

In [28]:
df.groupby('Industry')['Valuation ($B)'].agg(
    ['count', 'sum', 'mean']
).sort_values('sum', ascending=False).head(10)

                                     count     sum      mean
Industry
Fintech                                205  784.82  3.828390
Internet software & services           192  556.13  2.896510
E-commerce & direct-to-consumer        107  325.39  3.041028
Artificial intelligence                 71  308.39  4.343521
Other                                   56  265.20  4.735714
Health                                  69  182.52  2.645217
Supply chain, logistics, & delivery     57  174.76  3.065965
Data management & analytics             41  135.84  3.313171
Cybersecurity                           49  122.70  2.504082
Hardware                                33  101.15  3.065152

Which years produced the most unicorns?

In [29]:
df['Year Joined'].value_counts().sort_index()

Year Joined
2007      1
2011      2
2012      4
2013      3
2014     13
2015     35
2016     21
2017     44
2018    103
2019    107
2020    107
2021    514
2022     83
Name: count, dtype: int64

Which countries have the most unicorns
Which countries have the highest total valuation
Which countries have the highest average valuation

In [30]:
df.groupby('Country')['Valuation ($B)'].agg(
    ['count','sum','mean']
).sort_values('sum', ascending=False).head(10)

                count      sum       mean
Country
United States     536  1829.74   3.413694
China             168   572.69   3.408869
India              63   187.05   2.969048
United Kingdom     42   177.68   4.230476
Germany            24    66.70   2.779167
Sweden              6    60.52  10.086667
Australia           6    50.60   8.433333
France             24    49.87   2.077917
Canada             19    49.03   2.580526
Israel             20    38.42   1.921000

In [31]:
df.to_csv('unicorn_clean.csv', index=False)

In [32]:
df = df.rename(columns={
    'Valuation ($B)': 'valuation_billion',
    'Date Joined': 'date_joined',
    'Founded Year': 'founded_year',
    'Total Raised': 'total_raised',
    'Investors Count': 'investors_count',
    'Deal Terms': 'deal_terms',
    'Portfolio Exits': 'portfolio_exits',
    'Select Inverstors': 'select_investors'
})

In [33]:
df.to_csv('unicorn_clean.csv', index=False)